- robot: ADA
  kinbody: glass
  action: move
  sample_goal: True
  TSRs:
     - Tw_e: [[ 0., 0., -1., -0.22], [-1., 0., 0., 0.1], [0., 1., 0., 0.28], [0., 0., 0., 1.]]
       Bw: [[ 0., 0. ], [0., 0.], [-0.02, 0.02], [0., 0.], [0., 0.], [0, 0]]





